### ISSUE TITLE
Module depency decrease

### ISSUE THREAD

**Issue by lancew** [dsully/perl-crypt-openssl-pkcs12#19]
Would it be possible to make Test::Pod::Coverage, Pod::Coverage, etc author/testing only requirements?

When installing with carton the snapshot file gains the following:

```
  Crypt-OpenSSL-PKCS12-0.8
    pathname: J/JO/JONASBN/Crypt-OpenSSL-PKCS12-0.8.tar.gz
    provides:
      Crypt::OpenSSL::PKCS12 0.8
    requirements:
      ExtUtils::MakeMaker 6.36
      Pod::Coverage 0.19
      Test::More 0.47
      Test::Pod::Coverage 1.08
      perl 5.005
```

**Comment by jonasbn** [comment]
Hi @lancew 

**Crypt::OpenSSL::PKCS12** uses [Module::Install](https://metacpan.org/pod/distribution/Module-Install/lib/Module/Install.pod) and specifies the 3 distributions you mention as **test** requirements.

```perl
test_requires 'Test::Pod::Coverage' => '1.08';
test_requires 'Pod::Coverage' => '0.19';
test_requires 'Test::More' => '0.47';
```
Ref: [`Makefile.PL`](https://github.com/dsully/perl-crypt-openssl-pkcs12/blob/master/Makefile.PL)

So some other part of the toolchain interprets this.

What does your `cpanfile` look like, since it must be the foundation of your `cpanfile.snapshot` and how was it generated/created - since the _snapshot_ generation is obvious and you described that already :-)

jonasbn

**Comment by lancew** [comment]
I shall have a dig into it later and let you know

**Comment by jonasbn** [comment]
Hi @lancew,

I have not heard more from you on this issue. Releases 0.9 and 0.10 has been released to CPAN, please let me know if you still observe the issue. I am closing this issue for now.

jonasbn
