### ISSUE TITLE
Decreasing version number warning from PAUSE

### ISSUE THREAD

**Issue by jonasbn** [dsully/perl-crypt-openssl-pkcs12#28]
# Issue Template

## Description

**PAUSE** reports decreasing version number when indexing.

> The following report has been written by the PAUSE namespace indexer.
> Please contact modules@perl.org if there are any open questions.
> 
>  User: JONASBN (jonasbn)
>  Distribution file: Crypt-OpenSSL-PKCS12-0.10.tar.gz
>  Number of files: 31
>  *.pm files: 14
>  README: Crypt-OpenSSL-PKCS12-0.10/README
>  META-File: Crypt-OpenSSL-PKCS12-0.10/META.yml
>  META-Parser: Parse::CPAN::Meta 1.4414
>  META-driven index: no
>  Timestamp of file: Wed Mar 14 07:20:24 2018 UTC
>  Time of this run: Wed Mar 14 07:21:56 2018 UTC
> 
> Status of this distro: Decreasing version number
> ================================================
> 
> 
> The following packages (grouped by status) have been found in the distro:
> 
> Status: Decreasing version number
> =================================
> 
>     module : Crypt::OpenSSL::PKCS12
>     version: 0.10
>     in file: Crypt-OpenSSL-PKCS12-0.10/PKCS12.pm
>     status : Not indexed because Crypt-OpenSSL-PKCS12-0.9/PKCS12.pm in
>             J/JO/JONASBN/Crypt-OpenSSL-PKCS12-0.9.tar.gz has a higher
>             version number (0.9)
> 
> __END__

### Expected behaviour

No warnings would be preferred

### Actual behaviour

Warning from **PAUSE**

## Crypt::OpenSSL::PKCS12 version

0.10

## Output, if available

Please see the description above.

## Step by step guide to reproducing the issue

This would require a new upload to PAUSE. I am just wondering if we are doing something wrong.

**Comment by jonasbn** [comment]
Hmrmf, pondering re-release of 0.10 as 1.00

`$ perl -e 'print "Houston we have a problem\n" if 0.10 < 0.9'`

**Comment by jonasbn** [comment]
Closed release 1.0 a re-release of 0.10 addressing the issue described here.

**Comment by jonasbn** [comment]
New report from PAUSE on the re-release as 1.0:

> The following report has been written by the PAUSE namespace indexer.
> Please contact modules@perl.org if there are any open questions.
> 
>  User: JONASBN (jonasbn)
>  Distribution file: Crypt-OpenSSL-PKCS12-1.0.tar.gz
>  Number of files: 31
>  *.pm files: 14
>  README: Crypt-OpenSSL-PKCS12-1.0/README
>  META-File: Crypt-OpenSSL-PKCS12-1.0/META.yml
>  META-Parser: Parse::CPAN::Meta 1.4414
>  META-driven index: no
>  Timestamp of file: Mon Mar 19 20:25:55 2018 UTC
>  Time of this run: Mon Mar 19 20:27:27 2018 UTC
> 
> Status of this distro: OK
> =========================
> 
> 
> The following packages (grouped by status) have been found in the distro:
> 
> Status: Successfully indexed
> ============================
> 
>     module : Crypt::OpenSSL::PKCS12
>     version: 1.0
>     in file: Crypt-OpenSSL-PKCS12-1.0/PKCS12.pm
>     status : indexed
> 
> __END__

**Comment by Grinnz** [comment]
Versions in Perl are abnormal and come in two forms: decimal numbers and (the usual) dotted-decimal sequences. They are differentiated based on whether there is a leading 'v' and whether there is more than one separator, if either of those is true then it's interpreted as a sequence of integers.

Otherwise, as with this module's versions, it's interpreted as a decimal number. This means that '0.10' and '0.1' are the same version, and both are less than '0.9'.

For conversion and comparison between the two, each segment of the dotted-decimal form is considered to be 3 decimal places of the decimal number form. So for example '0.1' is the same as 'v0.100.0', and 'v0.1' is the same as '0.001'.

Despite the dotted-decimal form being more 'standard', it's not as supported in old versions of the Perl toolchain so it's generally preferred to stick with the decimal form. If you do change forms it's recommended to do a major version change to prevent any ambiguity. In both cases versions should always be represented as a string (as this module does).

Hope this helps explain what happened. More info available at the [version](https://metacpan.org/pod/version) docs.

**Comment by jonasbn** [comment]
Hi @Grinnz 

I fast became clear to me what had happened, I had just my head up my a...ttic, when I made the release so I did not spot the difference in the version number scheme used. I am used to the 2 part decimals like `X.YY`, which used to be CPAN _de facto standard_, which we also use at my work for our Perl distributions, everything else is [semver](https://semver.org/).

Thanks for the explanation anyhow, which makes perfect sense. Well I am not sure I find the Perl versioning sensible, but the decimal number comparison you mention is logical and points to my (human) error.
